version: '3'

networks:
  integration_test:
    driver: bridge

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - integration_test
  flyway:
    image: flyway/flyway:7
    command: -url=jdbc:postgresql://postgres/postgres -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate info
    volumes:
      - ./test/migration/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - integration_test
